CREATE VIEW TITLE_WINS (
    TITLE_WIN_WRESTLER,
    TITLE_WIN_CHAMPIONSHIP,
    TITLE_WIN_MATCH
    )
    AS SELECT WRESTLER_IN_MATCH.Ring_Name, MATCH.Defence_Of, WRESTLER_IN_MATCH.Match_ID
    FROM WRESTLER_IN_MATCH, MATCH
    WHERE WRESTLER_IN_MATCH.Match_ID = Match_ID AND MATCH.Defence_Of IS NOT NULL AND WRESTLER_IN_MATCH.Win = 1;